# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0004_auto_20180504_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='like',
            new_name='photo',
        ),
    ]
